# GCP Settings
gcp_project   = "aa-study"
gcp_region    = "us-central1"
gcp_auth_file = "aa-study-b2fb4c6587c9.json"
bucket_name   = "bucket-landing-falabella-logs"
project_number = 835573758019
origin_system = "omnichannel"
business_unit = "bfa"
country = "cl"
environment = "dev"
transaction_example = "super_avance"
type = "raw"